name       : python-munkres
version    : 1.1.2
release    : 3
source     :
    - https://github.com/bmc/munkres/archive/release-1.1.2.tar.gz : 0a25570d1498d4ce86b6ed151f3afa1da7318deac56db25100ccbdb9b12625c3
license    : Apache-2.0
component  : programming.python
summary    : Munkres algorithm for Python
description: |
    The Munkres module provides an O(n^3) implementation of the Munkres algorithm (also called the Hungarian algorithm or the Kuhn-Munkres algorithm). The algorithm models an assignment problem as an NxM cost matrix, where each element represents the cost of assigning the ith worker to the jth job, and it figures out the least-cost solution, choosing a single item from each row and column in the matrix, such that no row and no column are used more than once.
setup      : |
    %python3_setup
install    : |
    %python3_install
