name       : python-munkres
version    : 1.0.9
release    : 2
source     :
    - https://github.com/bmc/munkres/archive/release-1.0.9.tar.gz : 1dae30b882f409bab8d913af7bbf41877359b1ece3fa0ea31d6486a454f3493b
license    : Apache-2.0
component  : programming.python
summary    : Munkres algorithm for Python
description: |
    The Munkres module provides an O(n^3) implementation of the Munkres algorithm (also called the Hungarian algorithm or the Kuhn-Munkres algorithm). The algorithm models an assignment problem as an NxM cost matrix, where each element represents the cost of assigning the ith worker to the jth job, and it figures out the least-cost solution, choosing a single item from each row and column in the matrix, such that no row and no column are used more than once.
builddeps  :
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
